### ISSUE TITLE
Другой инструмент

### ISSUE THREAD

**Issue by makc-ar** [flatz/bioshock#1]
Здравствуй! Спасибо огромное тебе за инструмент, мы импортировали для PS4 текст для народа и всё работает нормально в игре. Прикрутили ещё озвучку для игры. Хотим прикрутить текстуры и сделать релиз, но столкнулись с файлами  .xxx и .tfc. Сможешь посмотреть эти файлы? Вот такие они https://www65.zippyshare.com/v/vbVqQnqO/file.html

**Comment by flatz** [comment]
Насколько помню, это обычные форматы Unreal Engine, в tfc, насколько помню, данные текстур  подряд идут, а xxx это переименованный upk. Тут вам надо смотреть в сторону моддинга игр на его основе, к сожалению, я им очень мало занимался, то, что делал - это запихивал текстуры кириллических шрифтов в конец файла, а потом правил оригинальные смещения/размеры, чтобы они указывали на мои. Больше, к сожалению, у меня не было и нет времени заниматься им.

**Comment by makc-ar** [comment]
Надо будет попробовать метод в конец файла. Ещё хотел спросить тебя за Borderlands 2 файла с текстом Coalesced_INT.bin. Сможешь посмотреть http://sendfile.su/1436607 его? Делаем перевод для Borderlands The Handsome Collection и наткнулись на файл с текстом Coalesced_INT.bin. Странный файл, который не берут инструменты всякие.

**Comment by flatz** [comment]
К сожалению, нет сейчас свободного времени на разбор игр. Так что вряд ли смогу тебе помочь. Попроси ребят с Xentax и типовых ресурсов, может чем-то помогут.
